services:
  - type: web
    name: tipa-app
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips="*"
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        value: TipaPayBot
      - key: VERIFY_ET_API_KEY
        sync: false
      - key: VERIFY_ET_BASE_URL
        value: https://verify.et
      - key: CHECK_ET_API_KEY
        sync: false
      - key: CHECK_ET_BASE_URL
        value: https://api.check.et/api/v1
      - key: JUSTVERIFY_API_KEY
        sync: false
      - key: JUSTVERIFY_BASE_URL
        value: https://justverify.et
      - key: DATABASE_URL
        fromDatabase:
          name: tipa-db
          property: connectionString
      - key: PLATFORM_FEE_BIRR
        value: "0.0"
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: tipa-db
    databaseName: tipa_db
    user: tipa_user
    plan: free
